spring:
  application:
    name: sugarcat

  profiles:
    active: local
    include: secret

  # JPA 공통
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100

  cache:
    type: caffeine
    cache-names:
      - onboardingStatus
      - userMe
      - userNotificationSettings
      - catInfo
      - mealSchedules
      - bloodSugarSchedules
      - insulinSchedules
      - dailyMealRecords
      - dailyBloodSugarRecords
      - dailyInsulinRecords
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30m

# 서버 설정
server:
  address: 0.0.0.0
  port: 8080

# 로깅
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace