# localhost postgreSQL 설정입니다.
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sugarcat
    username: postgres
    password: pg1234
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never # schema.sql 처음 초기화는 수동으로

  jpa:
    hibernate:
      ddl-auto: validate
      # update -> 엔티티 기준으로 DB 수정
      # validate -> 엔티티와 DB가 맞는지만 검사
    show-sql: false