jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800000} #30분
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1209600000} #14일

apple:
  login:
    client-id: ${APPLE_LOGIN_CLIENT_ID}

  apns:
    bundle-id: ${APNS_BUNDLE_ID}
    key-id: ${APNS_KEY_ID}
    team-id: ${APNS_TEAM_ID}
    private-key-path: ${APNS_PRIVATE_KEY_PATH} # .p8 파일 경로
    production: ${APNS_PRODUCTION:false} # 개발/운영 APNs 서버 구분